import React from "react";

import "./sidebar.css";

export const Sidebar = ({ handleChange, category }) => {
  
  return (
    <div className="sidebar-container">
      <h1>Zapatillas</h1>
      <hr />
      <h2>Filtrar</h2>
      <div className="accordion" id="category">
        <button
          className="accordion-button collapsed sidebar-container__filter-header"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#collapseOne"
          aria-expanded="false"
          aria-controls="collapseOne"
        >
          <h3>Categoría</h3>
        </button>
        <ul
          id="collapseOne"
          className="collapse"
          aria-labelledby="headingOne"
          data-bs-parent="#category"
        >
          <li>
            <button
              type="button"
              name="category"
              value="shoes"
              onClick={handleChange}
            >
              Zapatillas
            </button>
          </li>
          <li>
            <button
              type="button"
              name="category"
              value="zapatos"
              onClick={handleChange}
            >
              Zapatos
            </button>
          </li>
          <li>
            <button
              type="button"
              name="category"
              value="botas"
              onClick={handleChange}
            >
              Botas
            </button>
          </li>
          <li>
            <button
              type="button"
              name="category"
              value="sandalias"
              onClick={handleChange}
            >
              Sandalias
            </button>
          </li>
          <li>
            <button
              type="button"
              name="category"
              value="pantuflas"
              onClick={handleChange}
            >
              Pantuflas
            </button>
          </li>
        </ul>
      </div>
      <div className="accordion" id="waist">
        <button
          className="accordion-button collapsed sidebar-container__filter-header"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#collapse-waist"
          aria-expanded="false"
          aria-controls="collapse-waist"
        >
          <h3>Talle</h3>
        </button>
        <ul
          id="collapse-waist"
          className="collapse"
          aria-labelledby="headingTwo"
          data-bs-parent="#waist"
        >
          <li>
            <button
              type="button"
              name="waist"
              value="36"
              onClick={handleChange}
            >
              36
            </button>
          </li>
          <li>
            <button
              type="button"
              name="waist"
              value="38"
              onClick={handleChange}
            >
              38
            </button>
          </li>
          <li>
            <button
              type="button"
              name="waist"
              value="40"
              onClick={handleChange}
            >
              40
            </button>
          </li>
          <li>
            <button
              type="button"
              name="waist"
              value="42"
              onClick={handleChange}
            >
              42
            </button>
          </li>
          <li>
            <button
              type="button"
              name="waist"
              value="44"
              onClick={handleChange}
            >
              44
            </button>
          </li>
          {category.waist ? (
            <li>
              <button
                className="clear-filter"
                type="button"
                name="waist"
                value=""
                onClick={handleChange}
              >
                Limpiar Filtro
              </button>
            </li>
          ) : null}
        </ul>
      </div>
      <div className="accordion" id="color">
        <button
          className="accordion-button collapsed sidebar-container__filter-header"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#collapse-color"
          aria-expanded="false"
          aria-controls="collapse-color"
        >
          <h3>Color</h3>
        </button>
        <ul
          id="collapse-color"
          className="collapse"
          aria-labelledby="headingThree"
          data-bs-parent="#color"
        >
          <li>
            <button
              type="button"
              name="color"
              value="white"
              onClick={handleChange}
            >
              Blanco
            </button>
          </li>
          <li>
            <button
              type="button"
              name="color"
              value="black"
              onClick={handleChange}
            >
              Negro
            </button>
          </li>
          <li>
            <button
              type="button"
              name="color"
              value="green"
              onClick={handleChange}
            >
              Verde
            </button>
          </li>
          <li>
            <button
              type="button"
              name="color"
              value="Blue"
              onClick={handleChange}
            >
              Azul
            </button>
          </li>
          <li>
            <button
              type="button"
              name="color"
              value="yellow"
              onClick={handleChange}
            >
              Amarillo
            </button>
          </li>
          {category.color ? (
            <li>
              <button
                type="button"
                name="color"
                value=""
                onClick={handleChange}
              >
                Limpiar Filtro
              </button>
            </li>
          ) : null}
        </ul>
      </div>
    </div>
  );
};
